# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/System_design_FPU_ip_0_0.xci
# IP: The module: 'System_design_FPU_ip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_add_d/alu_add_d.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_add_d || ORIG_REF_NAME==alu_add_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_add_f/alu_add_f.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_add_f || ORIG_REF_NAME==alu_add_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_sub_f/alu_sub_f.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_sub_f || ORIG_REF_NAME==alu_sub_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_sub_d/alu_sub_d.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_sub_d || ORIG_REF_NAME==alu_sub_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_mul_f/alu_mul_f.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_mul_f || ORIG_REF_NAME==alu_mul_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_mul_d/alu_mul_d.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_mul_d || ORIG_REF_NAME==alu_mul_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_div_f/alu_div_f.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_div_f || ORIG_REF_NAME==alu_div_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_div_d/alu_div_d.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_div_d || ORIG_REF_NAME==alu_div_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_rec_f/alu_rec_f.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_rec_f || ORIG_REF_NAME==alu_rec_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_rec_d/alu_rec_d.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_rec_d || ORIG_REF_NAME==alu_rec_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_sqrt_f/alu_sqrt_f.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_sqrt_f || ORIG_REF_NAME==alu_sqrt_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_sqrt_d/alu_sqrt_d.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_sqrt_d || ORIG_REF_NAME==alu_sqrt_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_log_f/alu_log_f.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_log_f || ORIG_REF_NAME==alu_log_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_log_d_1/alu_log_d.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_log_d || ORIG_REF_NAME==alu_log_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_exp_f/alu_exp_f.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_exp_f || ORIG_REF_NAME==alu_exp_f} -quiet] -quiet

# IP: D:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/System_design_FPU_ip_0_0.xci
# IP: The module: 'System_design_FPU_ip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_add_d/alu_add_d.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_add_d || ORIG_REF_NAME==alu_add_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_add_f/alu_add_f.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_add_f || ORIG_REF_NAME==alu_add_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_sub_f/alu_sub_f.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_sub_f || ORIG_REF_NAME==alu_sub_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_sub_d/alu_sub_d.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_sub_d || ORIG_REF_NAME==alu_sub_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_mul_f/alu_mul_f.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_mul_f || ORIG_REF_NAME==alu_mul_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_mul_d/alu_mul_d.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_mul_d || ORIG_REF_NAME==alu_mul_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_div_f/alu_div_f.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_div_f || ORIG_REF_NAME==alu_div_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_div_d/alu_div_d.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_div_d || ORIG_REF_NAME==alu_div_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_rec_f/alu_rec_f.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_rec_f || ORIG_REF_NAME==alu_rec_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_rec_d/alu_rec_d.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_rec_d || ORIG_REF_NAME==alu_rec_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_sqrt_f/alu_sqrt_f.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_sqrt_f || ORIG_REF_NAME==alu_sqrt_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_sqrt_d/alu_sqrt_d.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_sqrt_d || ORIG_REF_NAME==alu_sqrt_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_log_f/alu_log_f.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_log_f || ORIG_REF_NAME==alu_log_f} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_log_d_1/alu_log_d.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_log_d || ORIG_REF_NAME==alu_log_d} -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_FPU_ip_0_0/src/alu_exp_f/alu_exp_f.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==alu_exp_f || ORIG_REF_NAME==alu_exp_f} -quiet] -quiet
