# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/System_design/System_design.bd
# Block Designs: The module: 'System_design' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/System_design/ip/System_design_FPU_ip_0_0/System_design_FPU_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_design_FPU_ip_0_0 || ORIG_REF_NAME==System_design_FPU_ip_0_0} -quiet] -quiet

# IP: bd/System_design/ip/System_design_processing_system7_0_0/System_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_design_processing_system7_0_0 || ORIG_REF_NAME==System_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/System_design/ip/System_design_ps7_0_axi_periph_0/System_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==System_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/System_design/ip/System_design_rst_ps7_0_100M_0/System_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==System_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/System_design/ip/System_design_auto_pc_0/System_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_design_auto_pc_0 || ORIG_REF_NAME==System_design_auto_pc_0} -quiet] -quiet

# XDC: bd/System_design/System_design_ooc.xdc
