# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_processing_system7_0_0/System_design_processing_system7_0_0.xci
# IP: The module: 'System_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_processing_system7_0_0/System_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_processing_system7_0_0/System_design_processing_system7_0_0.xci
# IP: The module: 'System_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_projects/PZ_FPU/PZ_FPU.srcs/sources_1/bd/System_design/ip/System_design_processing_system7_0_0/System_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
